 
// This file is to support autoCanBuild.html, and possibly others.
// It provides a means of accessing relevant scenario information in order
// to build code.

// Unit Types
const unitList = [
	{name:"Red Army Group", id:0,code:"object.uRedArmyGroup"},
	{name:"Construction Team", id:1,code:"object.uConstructionTeam"},
	{name:"Bofors 40mm", id:2,code:"object.uBofors40mm"},
	{name:"Early Radar", id:3,code:"object.uEarlyRadar"},
	{name:"Advanced Radar", id:4,code:"object.uAdvancedRadar"},
	{name:"Fw200", id:5,code:"object.uFw200"},
	{name:"Freight Train", id:6,code:"object.uFreightTrain"},
	{name:"Railyard", id:7,code:"object.uRailyard"},
	{name:"Aerial Photos", id:8,code:"object.uAerialPhotos"},
	{name:"Sdkfz 7/2", id:9,code:"object.uSdkfz72"},
	{name:"88mm Flak Battery", id:10,code:"object.u88mmFlakBattery"},
	{name:"Flak Train", id:11,code:"object.uFlakTrain"},
	{name:"Me109G6", id:12,code:"object.uMe109G6"},
	{name:"Me109G14", id:13,code:"object.uMe109G14"},
	{name:"Me109K4", id:14,code:"object.uMe109K4"},
	{name:"Fw190A5", id:15,code:"object.uFw190A5"},
	{name:"Fw190A8", id:16,code:"object.uFw190A8"},
	{name:"Fw190D9", id:17,code:"object.uFw190D9"},
	{name:"Ta152", id:18,code:"object.uTa152"},
	{name:"Military Port", id:19,code:"object.uMilitaryPort"},
	{name:"Me110", id:20,code:"object.uMe110"},
	{name:"Me410", id:21,code:"object.uMe410"},
	{name:"Ju88C", id:22,code:"object.uJu88C"},
	{name:"Ju88G", id:23,code:"object.uJu88G"},
	{name:"He219", id:24,code:"object.uHe219"},
	{name:"He162", id:25,code:"object.uHe162"},
	{name:"Me163", id:26,code:"object.uMe163"},
	{name:"Me262", id:27,code:"object.uMe262"},
	{name:"Ju87G", id:28,code:"object.uJu87G"},
	{name:"Fw190F8", id:29,code:"object.uFw190F8"},
	{name:"Do335", id:30,code:"object.uDo335"},
	{name:"Do217", id:31,code:"object.uDo217"},
	{name:"He277", id:32,code:"object.uHe277"},
	{name:"Arado234", id:33,code:"object.uArado234"},
	{name:"Go229", id:34,code:"object.uGo229"},
	{name:"Spitfire IX", id:35,code:"object.uSpitfireIX"},
	{name:"Spitfire XII", id:36,code:"object.uSpitfireXII"},
	{name:"Spitfire XIV", id:37,code:"object.uSpitfireXIV"},
	{name:"Hurricane IV", id:38,code:"object.uHurricaneIV"},
	{name:"Typhoon", id:39,code:"object.uTyphoon"},
	{name:"Tempest", id:40,code:"object.uTempest"},
	{name:"Meteor", id:41,code:"object.uMeteor"},
	{name:"Beaufighter", id:42,code:"object.uBeaufighter"},
	{name:"Mosquito NF Mk II", id:43,code:"object.uMosquitoNFMkII"},
	{name:"Mosquito NF Mk XIII", id:44,code:"object.uMosquitoNFMkXIII"},
	{name:"Industry", id:45,code:"object.uIndustry"},
	{name:"Fw190A5 - Rocket", id:46,code:"object.uFw190A5Rocket"},
	{name:"Fw190A8 - Rocket", id:47,code:"object.uFw190A8Rocket"},
	{name:"Me109G6 - Rocket", id:48,code:"object.uMe109G6Rocket"},
	{name:"Barrage Balloons", id:49,code:"object.uBarrageBalloons"},
	{name:"P-47D11", id:50,code:"object.uP47D11"},
	{name:"P-47D25", id:51,code:"object.uP47D25"},
	{name:"P-47D40", id:52,code:"object.uP47D40"},
	{name:"Experten", id:53,code:"object.uExperten"},
	{name:"P-38H", id:54,code:"object.uP38H"},
	{name:"P-38J", id:55,code:"object.uP38J"},
	{name:"P-51B", id:56,code:"object.uP51B"},
	{name:"P-51D", id:57,code:"object.uP51D"},
	{name:"P-80", id:58,code:"object.uP80"},
	{name:"Stirling", id:59,code:"object.uStirling"},
	{name:"Halifax", id:60,code:"object.uHalifax"},
	{name:"Lancaster", id:61,code:"object.uLancaster"},
	{name:"Pathfinder", id:62,code:"object.uPathfinder"},
	{name:"A-20", id:63,code:"object.uA20"},
	{name:"B-26", id:64,code:"object.uB26"},
	{name:"A-26", id:65,code:"object.uA26"},
	{name:"B-17F", id:66,code:"object.uB17F"},
	{name:"B-24J", id:67,code:"object.uB24J"},
	{name:"B-17G", id:68,code:"object.uB17G"},
	{name:"Battle Group German", id:69,code:"object.uBattleGroupGerman"},
	{name:"Depleted Battle Group German", id:70,code:"object.uDepletedBattleGroupGerman"},
	{name:"Egon Mayer", id:71,code:"object.uEgonMayer"},
	{name:"3.7-inch Flak", id:72,code:"object.u37inchFlak"},
	{name:"He111", id:73,code:"object.uHe111"},
	{name:"Battle Group Allied", id:74,code:"object.uBattleGroupAllied"},
	{name:"Depleted Battle Group Allied", id:75,code:"object.uDepletedBattleGroupAllied"},
	{name:"Sunderland", id:76,code:"object.uSunderland"},
	{name:"SAVE16", id:77,code:"object.uSAVE16"},
	{name:"Hermann Graf", id:78,code:"object.uHermannGraf"},
	{name:"Josef Priller", id:79,code:"object.uJosefPriller"},
	{name:"Adolf Galland", id:80,code:"object.uAdolfGalland"},
	{name:"Task Force (G)", id:81,code:"object.uTaskForceG"},
	{name:"Task Force (A)", id:82,code:"object.uTaskForceA"},
	{name:"332nd FG", id:83,code:"object.u332ndFG"},
	{name:"15th AF Bombers", id:84,code:"object.u15thAFBombers"},
	{name:"Aircraft Factory", id:85,code:"object.uAircraftFactory"},
	{name:"Me109G14 - Rocket", id:86,code:"object.uMe109G14Rocket"},
	{name:"SAVE17", id:87,code:"object.uSAVE17"},
	{name:"Refinery", id:88,code:"object.uRefinery"},
	{name:"Gunther Rall", id:89,code:"object.uGuntherRall"},
	{name:"Walter Nowotny", id:90,code:"object.uWalterNowotny"},
	{name:"Urban Center", id:91,code:"object.uUrbanCenter"},
	{name:"Whirlwind", id:92,code:"object.uWhirlwind"},
	{name:"B-25", id:93,code:"object.uB25"},
	{name:"Gun Battery", id:94,code:"object.uGunBattery"},
	{name:"P-61", id:95,code:"object.uP61"},
	{name:"Mosquito B.IV", id:96,code:"object.uMosquitoBIV"},
	{name:"Francis Gabreski", id:97,code:"object.uFrancisGabreski"},
	{name:"George Preddy", id:98,code:"object.uGeorgePreddy"},
	{name:"John Braham", id:99,code:"object.uJohnBraham"},
	{name:"Johnnie Johnson", id:100,code:"object.uJohnnieJohnson"},
	{name:"Window", id:101,code:"object.uWindow"},
	{name:"H.W. Schnaufer", id:102,code:"object.uHWSchnaufer"},
	{name:"Eirch Hartmann", id:103,code:"object.uEirchHartmann"},
	{name:"Panzer Division", id:104,code:"object.uPanzerDivision"},
	{name:"Damaged B-17F", id:105,code:"object.uDamagedB17F"},
	{name:"Neutral Territory", id:106,code:"object.uNeutralTerritory"},
	{name:"Damaged B-17G", id:107,code:"object.uDamagedB17G"},
	{name:"P-38L", id:108,code:"object.uP38L"},
	{name:"Critical Industry", id:109,code:"object.uCriticalIndustry"},
	{name:"Gerhard Barkhorn", id:110,code:"object.uGerhardBarkhorn"},
	{name:"Aircraft Carrier", id:111,code:"object.uAircraftCarrier"},
	{name:"USAAF Ace", id:112,code:"object.uUSAAFAce"},
	{name:"RAF Ace", id:113,code:"object.uRAFAce"},
	{name:"Barrage", id:114,code:"object.uBarrage"},
	{name:"Convoy", id:115,code:"object.uConvoy"},
	{name:"SAVE18", id:116,code:"object.uSAVE18"},
	{name:"Yak-3", id:117,code:"object.uYak3"},
	{name:"Il-2", id:118,code:"object.uIl2"},
	{name:"3.7cm Flak", id:119,code:"object.u37cmFlak"},
	{name:"Ju-188 (PR)", id:120,code:"object.uJu188PR"},
	{name:"V1 Launch Site", id:121,code:"object.uV1LaunchSite"},
	{name:"V2 Launch Site", id:122,code:"object.uV2LaunchSite"},
	{name:"V1 Buzzbomb", id:123,code:"object.uV1Buzzbomb"},
	{name:"V2 Rocket", id:124,code:"object.uV2Rocket"},
	{name:"Mosquito (PR)", id:125,code:"object.uMosquitoPR"},
	{name:"Wolf Pack", id:126,code:"object.uWolfPack"},
]

// Tribes/Players
const tribeList = [
	{name:"Neutrals", id:0,code:"object.pNeutrals"},
	{name:"Allies", id:1,code:"object.pAllies"},
	{name:"Germans", id:2,code:"object.pGermans"},
	{name:"Events", id:3,code:"object.pEvents"},
	{name:"Not used", id:4,code:"object.pNotused"},
	{name:"Not used", id:5,code:"object.pNotused_"},
	{name:"Not used", id:6,code:"object.pNotused__"},
	{name:"Not used", id:7,code:"object.pNotused___"},
]

// Improvements
const improvementList = [
	{name:"Nothing", id:0,code:"object.iNothing"},
	{name:"Headquarters", id:1,code:"object.iHeadquarters"},
	{name:"NOT USED", id:2,code:"object.iNOTUSED"},
	{name:"Red Army", id:3,code:"object.iRedArmy"},
	{name:"Civilian Population I", id:4,code:"object.iCivilianPopulationI"},
	{name:"Fuel Refinery I", id:5,code:"object.iFuelRefineryI"},
	{name:"Aircraft Factory I", id:6,code:"object.iAircraftFactoryI"},
	{name:"Quartermaster", id:7,code:"object.iQuartermaster"},
	{name:"City I", id:8,code:"object.iCityI"},
	{name:"City II", id:9,code:"object.iCityII"},
	{name:"Fuel Refinery II", id:10,code:"object.iFuelRefineryII"},
	{name:"Civilian Population II", id:11,code:"object.iCivilianPopulationII"},
	{name:"Aircraft Factory II", id:12,code:"object.iAircraftFactoryII"},
	{name:"Critical Industry", id:13,code:"object.iCriticalIndustry"},
	{name:"Civilian Population III", id:14,code:"object.iCivilianPopulationIII"},
	{name:"Industry I", id:15,code:"object.iIndustryI"},
	{name:"Industry II", id:16,code:"object.iIndustryII"},
	{name:"Airbase", id:17,code:"object.iAirbase"},
	{name:"15th Air Force", id:18,code:"object.i15thAirForce"},
	{name:"OLD Industry III", id:19,code:"object.iOLDIndustryIII"},
	{name:"NOT USED", id:20,code:"object.iNOTUSED_"},
	{name:"NOT USED", id:21,code:"object.iNOTUSED__"},
	{name:"Fuel Refinery III", id:22,code:"object.iFuelRefineryIII"},
	{name:"City III", id:23,code:"object.iCityIII"},
	{name:"Rationing", id:24,code:"object.iRationing"},
	{name:"Railyards", id:25,code:"object.iRailyards"},
	{name:"Aircraft Factory III", id:26,code:"object.iAircraftFactoryIII"},
	{name:"Experimental Aircraft", id:27,code:"object.iExperimentalAircraft"},
	{name:"Firefighters", id:28,code:"object.iFirefighters"},
	{name:"Industry III", id:29,code:"object.iIndustryIII"},
	{name:"Docks", id:30,code:"object.iDocks"},
	{name:"NOT USED", id:31,code:"object.iNOTUSED___"},
	{name:"Jagdfliegerschule", id:32,code:"object.iJagdfliegerschule"},
	{name:"Wehrmacht", id:33,code:"object.iWehrmacht"},
	{name:"Military Port", id:34,code:"object.iMilitaryPort"},
	{name:"NOT USED", id:35,code:"object.iNOTUSED____"},
]

// Wonders
const wonderList = [
	{name:"NOT USED", id:0,code:"object.wNOTUSED"},
	{name:"NOT USED", id:1,code:"object.wNOTUSED_"},
	{name:"I.G. Farben", id:2,code:"object.wIGFarben"},
	{name:"NOT USED", id:3,code:"object.wNOTUSED__"},
	{name:"NOT USED", id:4,code:"object.wNOTUSED___"},
	{name:"NOT USED", id:5,code:"object.wNOTUSED____"},
	{name:"NOT USED", id:6,code:"object.wNOTUSED_____"},
	{name:"NOT USED", id:7,code:"object.wNOTUSED______"},
	{name:"Krupp Works", id:8,code:"object.wKruppWorks"},
	{name:"NOT USED", id:9,code:"object.wNOTUSED_______"},
	{name:"NOT USED", id:10,code:"object.wNOTUSED________"},
	{name:"Peenemünde", id:11,code:"object.wPeenemnde"},
	{name:"NOT USED", id:12,code:"object.wNOTUSED_________"},
	{name:"NOT USED", id:13,code:"object.wNOTUSED__________"},
	{name:"NOT USED", id:14,code:"object.wNOTUSED___________"},
	{name:"Adolf Hitler", id:15,code:"object.wAdolfHitler"},
	{name:"Jägernotprogramm", id:16,code:"object.wJgernotprogramm"},
	{name:"Albert Speer's Reforms", id:17,code:"object.wAlbertSpeersReforms"},
	{name:"56th Fighter Group", id:18,code:"object.w56thFighterGroup"},
	{name:"No.617 RAF", id:19,code:"object.wNo617RAF"},
	{name:"JG2 Richthofen", id:20,code:"object.wJG2Richthofen"},
	{name:"NOT USED", id:21,code:"object.wNOTUSED____________"},
	{name:"Arsenal of Democracy", id:22,code:"object.wArsenalofDemocracy"},
	{name:"NOT USED", id:23,code:"object.wNOTUSED_____________"},
	{name:"JG26 Schlageter", id:24,code:"object.wJG26Schlageter"},
	{name:"NOT USED", id:25,code:"object.wNOTUSED______________"},
	{name:"NOT USED", id:26,code:"object.wNOTUSED_______________"},
	{name:"NOT USED", id:27,code:"object.wNOTUSED________________"},
]

// Advances
const advancesList = [
	{name:"Interceptors I", id:0,code:"object.aInterceptorsI"},
	{name:"Interceptors II", id:1,code:"object.aInterceptorsII"},
	{name:"Interceptors III", id:2,code:"object.aInterceptorsIII"},
	{name:"Escort Fighters I", id:3,code:"object.aEscortFightersI"},
	{name:"Escort Fighters II", id:4,code:"object.aEscortFightersII"},
	{name:"Night Bombing I", id:5,code:"object.aNightBombingI"},
	{name:"Escort Fighters III", id:6,code:"object.aEscortFightersIII"},
	{name:"NOT USED", id:7,code:"object.aNOTUSED"},
	{name:"Cadillac of the Skies", id:8,code:"object.aCadillacoftheSkies"},
	{name:"1940s Tech I", id:9,code:"object.a1940sTechI"},
	{name:"Bomber Destroyers I", id:10,code:"object.aBomberDestroyersI"},
	{name:"Bomber Destroyers II", id:11,code:"object.aBomberDestroyersII"},
	{name:"Interceptors IV", id:12,code:"object.aInterceptorsIV"},
	{name:"Night Fighters I", id:13,code:"object.aNightFightersI"},
	{name:"Night Fighters II", id:14,code:"object.aNightFightersII"},
	{name:"The Grand Alliance", id:15,code:"object.aTheGrandAlliance"},
	{name:"Night Fighters III", id:16,code:"object.aNightFightersIII"},
	{name:"Advanced Radar I", id:17,code:"object.aAdvancedRadarI"},
	{name:"NOT USED", id:18,code:"object.aNOTUSED_"},
	{name:"Advanced Radar II", id:19,code:"object.aAdvancedRadarII"},
	{name:"Engines I", id:20,code:"object.aEnginesI"},
	{name:"NOT USED", id:21,code:"object.aNOTUSED__"},
	{name:"Engines II", id:22,code:"object.aEnginesII"},
	{name:"Engines III", id:23,code:"object.aEnginesIII"},
	{name:"Night Bombing II", id:24,code:"object.aNightBombingII"},
	{name:"Jabo I", id:25,code:"object.aJaboI"},
	{name:"Jabo II", id:26,code:"object.aJaboII"},
	{name:"Jabo III", id:27,code:"object.aJaboIII"},
	{name:"Engines IV", id:28,code:"object.aEnginesIV"},
	{name:"Experimental Design", id:29,code:"object.aExperimentalDesign"},
	{name:"Volksjäger", id:30,code:"object.aVolksjger"},
	{name:"NOT USED", id:31,code:"object.aNOTUSED___"},
	{name:"Centrifugal-Flow Engine", id:32,code:"object.aCentrifugalFlowEngine"},
	{name:"Axial-Flow Compressor", id:33,code:"object.aAxialFlowCompressor"},
	{name:"NOT USED", id:34,code:"object.aNOTUSED____"},
	{name:"NOT USED", id:35,code:"object.aNOTUSED_____"},
	{name:"Jet Fighters", id:36,code:"object.aJetFighters"},
	{name:"The Third Reich", id:37,code:"object.aTheThirdReich"},
	{name:"Jet Fighter Design", id:38,code:"object.aJetFighterDesign"},
	{name:"Jet Bombers I", id:39,code:"object.aJetBombersI"},
	{name:"Jet Bombers II", id:40,code:"object.aJetBombersII"},
	{name:"Wunderwaffe Program", id:41,code:"object.aWunderwaffeProgram"},
	{name:"Pulse-Jet Engines", id:42,code:"object.aPulseJetEngines"},
	{name:"Vergeltungswaffen 1", id:43,code:"object.aVergeltungswaffen1"},
	{name:"Rocketry", id:44,code:"object.aRocketry"},
	{name:"Vergeltungswaffen 2", id:45,code:"object.aVergeltungswaffen2"},
	{name:"Strategic Bombers I", id:46,code:"object.aStrategicBombersI"},
	{name:"Strategic Bombers II", id:47,code:"object.aStrategicBombersII"},
	{name:"Strategic Bombers III", id:48,code:"object.aStrategicBombersIII"},
	{name:"Window", id:49,code:"object.aWindow"},
	{name:"Tactical Bombers I", id:50,code:"object.aTacticalBombersI"},
	{name:"Tactical Bombers II", id:51,code:"object.aTacticalBombersII"},
	{name:"Tactical Bombers III", id:52,code:"object.aTacticalBombersIII"},
	{name:"Rocket Fighters", id:53,code:"object.aRocketFighters"},
	{name:"NOT USED", id:54,code:"object.aNOTUSED______"},
	{name:"1940s Tech II", id:55,code:"object.a1940sTechII"},
	{name:"1940s Tech III", id:56,code:"object.a1940sTechIII"},
	{name:"Jet Fighter Focus", id:57,code:"object.aJetFighterFocus"},
	{name:"Jägernotprogramm", id:58,code:"object.aJgernotprogramm"},
	{name:"Wilde Sau", id:59,code:"object.aWildeSau"},
	{name:"Night Bombing III", id:60,code:"object.aNightBombingIII"},
	{name:"Industry I", id:61,code:"object.aIndustryI"},
	{name:"Industry II", id:62,code:"object.aIndustryII"},
	{name:"Industry III", id:63,code:"object.aIndustryIII"},
	{name:"Fuel Production I", id:64,code:"object.aFuelProductionI"},
	{name:"Fuel Production II", id:65,code:"object.aFuelProductionII"},
	{name:"NOT USED", id:66,code:"object.aNOTUSED_______"},
	{name:"NOT USED", id:67,code:"object.aNOTUSED________"},
	{name:"Fuel Production III", id:68,code:"object.aFuelProductionIII"},
	{name:"War Economy", id:69,code:"object.aWarEconomy"},
	{name:"Rationing", id:70,code:"object.aRationing"},
	{name:"The Axis Powers", id:71,code:"object.aTheAxisPowers"},
	{name:"Jägerstab", id:72,code:"object.aJgerstab"},
	{name:"Foggia Airfields", id:73,code:"object.aFoggiaAirfields"},
	{name:"Operation Overlord Prep.", id:74,code:"object.aOperationOverlordPrep"},
	{name:"Operation Neptune", id:75,code:"object.aOperationNeptune"},
	{name:"Vistula-Oder Offensive", id:76,code:"object.aVistulaOderOffensive"},
	{name:"Tuskeegee Airmen", id:77,code:"object.aTuskeegeeAirmen"},
	{name:"Mass-Production Focus", id:78,code:"object.aMassProductionFocus"},
	{name:"High-Technology Focus", id:79,code:"object.aHighTechnologyFocus"},
	{name:"Argument for Jet Jabo", id:80,code:"object.aArgumentforJetJabo"},
	{name:"Jet Fighters Prioritized", id:81,code:"object.aJetFightersPrioritized"},
	{name:"1940s Tech IV", id:82,code:"object.a1940sTechIV"},
	{name:"Proximity Fuses", id:83,code:"object.aProximityFuses"},
	{name:"Aircraft Prototypes", id:84,code:"object.aAircraftPrototypes"},
	{name:"--Search for Long-Range Fighter", id:85,code:"object.aSearchforLongRangeFighter"},
	{name:"--The Allison-Powered Mustang", id:86,code:"object.aTheAllisonPoweredMustang"},
	{name:"Rolls-Royce Merlin 61 Refit", id:87,code:"object.aRollsRoyceMerlin61Refit"},
	{name:"Advanced Radar III", id:88,code:"object.aAdvancedRadarIII"},
	{name:"Delays", id:89,code:"object.aDelays"},
	{name:"Tactics I", id:90,code:"object.aTacticsI"},
	{name:"Tactics II", id:91,code:"object.aTacticsII"},
	{name:"Tactics III", id:92,code:"object.aTacticsIII"},
	{name:"Roam at Will", id:93,code:"object.aRoamatWill"},
	{name:"Long-Range Escorts Needed", id:94,code:"object.aLongRangeEscortsNeeded"},
	{name:"Albert Speer's Death", id:95,code:"object.aAlbertSpeersDeath"},
	{name:"Political Support I", id:96,code:"object.aPoliticalSupportI"},
	{name:"Political Support II", id:97,code:"object.aPoliticalSupportII"},
	{name:"Political Support III", id:98,code:"object.aPoliticalSupportIII"},
	{name:"Political Support IV", id:99,code:"object.aPoliticalSupportIV"},
]

// Cities
const cityLocationList = [
	{name:"Berlin", id:0, tribeId:2, code:"object.lBerlin", xyz:[363,71,0]},
	{name:"Dresden", id:1, tribeId:2, code:"object.lDresden", xyz:[369,89,0]},
	{name:"Prague", id:2, tribeId:2, code:"object.lPrague", xyz:[375,101,0]},
	{name:"Vienna", id:3, tribeId:2, code:"object.lVienna", xyz:[403,121,0]},
	{name:"Leipzig", id:4, tribeId:2, code:"object.lLeipzig", xyz:[352,90,0]},
	{name:"Merseburg", id:5, tribeId:2, code:"object.lMerseburg", xyz:[347,85,0]},
	{name:"Rostock", id:6, tribeId:2, code:"object.lRostock", xyz:[347,55,0]},
	{name:"Lüneburg", id:7, tribeId:2, code:"object.lLneburg", xyz:[323,73,0]},
	{name:"Hannover", id:8, tribeId:2, code:"object.lHannover", xyz:[306,82,0]},
	{name:"Bremen", id:9, tribeId:2, code:"object.lBremen", xyz:[299,63,0]},
	{name:"Wilhelmshaven", id:10, tribeId:2, code:"object.lWilhelmshaven", xyz:[293,59,0]},
	{name:"Düsseldorf", id:11, tribeId:2, code:"object.lDsseldorf", xyz:[271,79,0]},
	{name:"Cologne", id:12, tribeId:2, code:"object.lCologne", xyz:[272,86,0]},
	{name:"Essen", id:13, tribeId:2, code:"object.lEssen", xyz:[274,76,0]},
	{name:"Dortmund", id:14, tribeId:2, code:"object.lDortmund", xyz:[280,76,0]},
	{name:"Hamburg", id:15, tribeId:2, code:"object.lHamburg", xyz:[317,59,0]},
	{name:"Kiel", id:16, tribeId:2, code:"object.lKiel", xyz:[324,50,0]},
	{name:"Lübeck", id:17, tribeId:2, code:"object.lLbeck", xyz:[332,56,0]},
	{name:"Nurnburg", id:18, tribeId:2, code:"object.lNurnburg", xyz:[326,106,0]},
	{name:"Munich", id:19, tribeId:2, code:"object.lMunich", xyz:[332,120,0]},
	{name:"Friedrichshaven", id:20, tribeId:2, code:"object.lFriedrichshaven", xyz:[300,124,0]},
	{name:"Schweinfurt", id:21, tribeId:2, code:"object.lSchweinfurt", xyz:[315,101,0]},
	{name:"Frankfurt", id:22, tribeId:2, code:"object.lFrankfurt", xyz:[295,95,0]},
	{name:"Aarhus", id:23, tribeId:2, code:"object.lAarhus", xyz:[326,32,0]},
	{name:"Freiburg", id:24, tribeId:2, code:"object.lFreiburg", xyz:[277,119,0]},
	{name:"Karlsruhe", id:25, tribeId:2, code:"object.lKarlsruhe", xyz:[288,104,0]},
	{name:"Mannheim", id:26, tribeId:2, code:"object.lMannheim", xyz:[292,100,0]},
	{name:"Stuttgart", id:27, tribeId:2, code:"object.lStuttgart", xyz:[298,110,0]},
	{name:"Regensburg", id:28, tribeId:2, code:"object.lRegensburg", xyz:[344,108,0]},
	{name:"Linz", id:29, tribeId:2, code:"object.lLinz", xyz:[370,122,0]},
	{name:"Brest", id:30, tribeId:2, code:"object.lBrest", xyz:[90,94,0]},
	{name:"St. Nazaire", id:31, tribeId:2, code:"object.lStNazaire", xyz:[118,108,0]},
	{name:"Nantes", id:32, tribeId:2, code:"object.lNantes", xyz:[125,111,0]},
	{name:"La Rochelle", id:33, tribeId:2, code:"object.lLaRochelle", xyz:[127,125,0]},
	{name:"Bordeaux", id:34, tribeId:2, code:"object.lBordeaux", xyz:[130,142,0]},
	{name:"Cherbourg", id:35, tribeId:2, code:"object.lCherbourg", xyz:[142,84,0]},
	{name:"Le Havre", id:36, tribeId:2, code:"object.lLeHavre", xyz:[164,90,0]},
	{name:"Tours", id:37, tribeId:2, code:"object.lTours", xyz:[163,117,0]},
	{name:"Rouen", id:38, tribeId:2, code:"object.lRouen", xyz:[176,92,0]},
	{name:"Paris", id:39, tribeId:2, code:"object.lParis", xyz:[195,101,0]},
	{name:"Brussels", id:40, tribeId:2, code:"object.lBrussels", xyz:[230,84,0]},
	{name:"Amsterdam", id:41, tribeId:2, code:"object.lAmsterdam", xyz:[245,65,0]},
	{name:"The Hague", id:42, tribeId:2, code:"object.lTheHague", xyz:[234,70,0]},
	{name:"Rotterdam", id:43, tribeId:2, code:"object.lRotterdam", xyz:[241,71,0]},
	{name:"Antwerp", id:44, tribeId:2, code:"object.lAntwerp", xyz:[231,77,0]},
	{name:"Lille", id:45, tribeId:2, code:"object.lLille", xyz:[211,87,0]},
	{name:"Calais", id:46, tribeId:2, code:"object.lCalais", xyz:[199,77,0]},
	{name:"Lyon", id:47, tribeId:2, code:"object.lLyon", xyz:[212,140,0]},
	{name:"Brunswick", id:48, tribeId:2, code:"object.lBrunswick", xyz:[339,75,0]},
	{name:"Peenemünde", id:49, tribeId:2, code:"object.lPeenemnde", xyz:[375,61,0]},
	{name:"London", id:50, tribeId:1, code:"object.lLondon", xyz:[172,68,0]},
	{name:"Portsmouth", id:51, tribeId:1, code:"object.lPortsmouth", xyz:[154,72,0]},
	{name:"Bristol", id:52, tribeId:1, code:"object.lBristol", xyz:[139,65,0]},
	{name:"Swansea", id:53, tribeId:1, code:"object.lSwansea", xyz:[119,61,0]},
	{name:"Plymouth", id:54, tribeId:1, code:"object.lPlymouth", xyz:[110,72,0]},
	{name:"Cardiff", id:55, tribeId:1, code:"object.lCardiff", xyz:[131,63,0]},
	{name:"Liverpool", id:56, tribeId:1, code:"object.lLiverpool", xyz:[140,44,0]},
	{name:"Birmingham", id:57, tribeId:1, code:"object.lBirmingham", xyz:[150,54,0]},
	{name:"Manchester", id:58, tribeId:1, code:"object.lManchester", xyz:[151,43,0]},
	{name:"Nottingham", id:59, tribeId:1, code:"object.lNottingham", xyz:[164,48,0]},
	{name:"Sheffield", id:60, tribeId:1, code:"object.lSheffield", xyz:[167,41,0]},
	{name:"Colchester", id:61, tribeId:1, code:"object.lColchester", xyz:[193,65,0]},
	{name:"Hull", id:62, tribeId:1, code:"object.lHull", xyz:[181,43,0]},
	{name:"Newcastle", id:63, tribeId:1, code:"object.lNewcastle", xyz:[171,27,0]},
	{name:"Edinburgh", id:64, tribeId:1, code:"object.lEdinburgh", xyz:[163,13,0]},
	{name:"Glasgow", id:65, tribeId:1, code:"object.lGlasgow", xyz:[137,11,0]},
	{name:"Belfast", id:66, tribeId:1, code:"object.lBelfast", xyz:[112,22,0]},
	{name:"Carlisle", id:67, tribeId:1, code:"object.lCarlisle", xyz:[152,24,0]},
	{name:"Leeds", id:68, tribeId:1, code:"object.lLeeds", xyz:[166,32,0]},
	{name:"Russian Front", id:69, tribeId:1, code:"object.lRussianFront", xyz:[406,74,0]},
	{name:"Italian Theatre", id:70, tribeId:1, code:"object.lItalianTheatre", xyz:[345,145,0]},
	{name:"Schiphol AF", id:71, tribeId:2, code:"object.lSchipholAF", xyz:[240,66,0]},
	{name:"Schiphol (N)", id:72, tribeId:2, code:"object.lSchipholN", xyz:[240,66,2]},
	{name:"Woensdrecht AF", id:73, tribeId:2, code:"object.lWoensdrechtAF", xyz:[223,79,0]},
	{name:"Woensdrecht (N)", id:74, tribeId:2, code:"object.lWoensdrechtN", xyz:[223,79,2]},
	{name:"Beaumont AF", id:75, tribeId:2, code:"object.lBeaumontAF", xyz:[165,101,0]},
	{name:"Beaumont (N)", id:76, tribeId:2, code:"object.lBeaumontN", xyz:[165,101,2]},
	{name:"Vannes AF", id:77, tribeId:2, code:"object.lVannesAF", xyz:[113,105,0]},
	{name:"Manston AF", id:78, tribeId:1, code:"object.lManstonAF", xyz:[191,73,0]},
	{name:"Boxted AF", id:79, tribeId:1, code:"object.lBoxtedAF", xyz:[197,63,0]},
	{name:"Croydon AF", id:80, tribeId:1, code:"object.lCroydonAF", xyz:[173,75,0]},
	{name:"Bolt Head AF", id:81, tribeId:1, code:"object.lBoltHeadAF", xyz:[117,71,0]},
	{name:"Duxford AF", id:82, tribeId:1, code:"object.lDuxfordAF", xyz:[176,60,0]},
	{name:"Ridgewell AF", id:83, tribeId:1, code:"object.lRidgewellAF", xyz:[181,57,0]},
	{name:"Winkton AF", id:84, tribeId:1, code:"object.lWinktonAF", xyz:[148,72,0]},
	{name:"Dumfries AF(N)", id:85, tribeId:1, code:"object.lDumfriesAFN", xyz:[149,17,2]},
	{name:"Woodford AF(N)", id:86, tribeId:1, code:"object.lWoodfordAFN", xyz:[154,48,2]},
	{name:"Winkton AF(N)", id:87, tribeId:1, code:"object.lWinktonAFN", xyz:[148,72,2]},
	{name:"Bolt Head AF(N)", id:88, tribeId:1, code:"object.lBoltHeadAFN", xyz:[117,71,2]},
	{name:"Croydon AF(N)", id:89, tribeId:1, code:"object.lCroydonAFN", xyz:[173,75,2]},
	{name:"Manston AF (N)", id:90, tribeId:1, code:"object.lManstonAFN", xyz:[191,73,2]},
	{name:"Boxted AF (N)", id:91, tribeId:1, code:"object.lBoxtedAFN", xyz:[197,63,2]},
	{name:"Drem AF", id:92, tribeId:1, code:"object.lDremAF", xyz:[168,16,0]},
	{name:"Woodford AF", id:93, tribeId:1, code:"object.lWoodfordAF", xyz:[154,48,0]},
	{name:"Dumfries AF", id:94, tribeId:1, code:"object.lDumfriesAF", xyz:[149,17,0]},
	{name:"Ridgewell AF(N)", id:95, tribeId:1, code:"object.lRidgewellAFN", xyz:[181,57,2]},
	{name:"Duxford AF(N)", id:96, tribeId:1, code:"object.lDuxfordAFN", xyz:[176,60,2]},
	{name:"Drem AF(N)", id:97, tribeId:1, code:"object.lDremAFN", xyz:[168,16,2]},
	{name:"Mullaghmore (N)", id:98, tribeId:1, code:"object.lMullaghmoreN", xyz:[108,18,2]},
	{name:"Dover", id:99, tribeId:1, code:"object.lDover", xyz:[185,75,0]},
	{name:"Mullaghmore AF", id:100, tribeId:1, code:"object.lMullaghmoreAF", xyz:[108,18,0]},
	{name:"Vannes (N)", id:101, tribeId:2, code:"object.lVannesN", xyz:[113,105,2]},
	{name:"Lannes AF", id:102, tribeId:2, code:"object.lLannesAF", xyz:[139,139,0]},
	{name:"Lannes (N)", id:103, tribeId:2, code:"object.lLannesN", xyz:[139,139,2]},
	{name:"Cormeilles AF", id:104, tribeId:2, code:"object.lCormeillesAF", xyz:[191,93,0]},
	{name:"Cormeilles (N)", id:105, tribeId:2, code:"object.lCormeillesN", xyz:[191,93,2]},
	{name:"Ostheim AF", id:106, tribeId:2, code:"object.lOstheimAF", xyz:[287,93,0]},
	{name:"Ostheim (N)", id:107, tribeId:2, code:"object.lOstheimN", xyz:[287,93,2]},
	{name:"Ophoven AF", id:108, tribeId:2, code:"object.lOphovenAF", xyz:[258,72,0]},
	{name:"Ophoven (N)", id:109, tribeId:2, code:"object.lOphovenN", xyz:[258,72,2]},
	{name:"Rheinsehlen AF", id:110, tribeId:2, code:"object.lRheinsehlenAF", xyz:[313,69,0]},
	{name:"Rheinsehlen (N)", id:111, tribeId:2, code:"object.lRheinsehlenN", xyz:[313,69,2]},
	{name:"Eggebek AF", id:112, tribeId:2, code:"object.lEggebekAF", xyz:[313,43,0]},
	{name:"Eggebek (N)", id:113, tribeId:2, code:"object.lEggebekN", xyz:[313,43,2]},
	{name:"Döberitz AF", id:114, tribeId:2, code:"object.lDberitzAF", xyz:[352,70,0]},
	{name:"Döberitz (N)", id:115, tribeId:2, code:"object.lDberitzN", xyz:[352,70,2]},
	{name:"Kolleda AF", id:116, tribeId:2, code:"object.lKolledaAF", xyz:[359,87,0]},
	{name:"Kolleda (N)", id:117, tribeId:2, code:"object.lKolledaN", xyz:[359,87,2]},
	{name:"Wels AF", id:118, tribeId:2, code:"object.lWelsAF", xyz:[364,122,0]},
	{name:"Wels (N)", id:119, tribeId:2, code:"object.lWelsN", xyz:[364,122,2]},
	{name:"Pocking AF", id:120, tribeId:2, code:"object.lPockingAF", xyz:[341,117,0]},
	{name:"Pocking (N)", id:121, tribeId:2, code:"object.lPockingN", xyz:[341,117,2]},
	{name:"Nellingand AF", id:122, tribeId:2, code:"object.lNellingandAF", xyz:[305,105,0]},
	{name:"Nellingand (N)", id:123, tribeId:2, code:"object.lNellingandN", xyz:[305,105,2]},
	{name:"Jever AF", id:124, tribeId:2, code:"object.lJeverAF", xyz:[288,64,0]},
	{name:"Jever (N)", id:125, tribeId:2, code:"object.lJeverN", xyz:[288,64,2]},
	{name:"Deelen AF", id:126, tribeId:2, code:"object.lDeelenAF", xyz:[249,71,0]},
	{name:"Deelen (N)", id:127, tribeId:2, code:"object.lDeelenN", xyz:[249,71,2]},
	{name:"Saint-Omer AF", id:128, tribeId:2, code:"object.lSaintOmerAF", xyz:[203,81,0]},
	{name:"Saint-Omer (N)", id:129, tribeId:2, code:"object.lSaintOmerN", xyz:[203,81,2]},
	{name:"Abbeville AF", id:130, tribeId:2, code:"object.lAbbevilleAF", xyz:[195,87,0]},
	{name:"Abbeville (N)", id:131, tribeId:2, code:"object.lAbbevilleN", xyz:[195,87,2]},
	{name:"Westerland AF", id:132, tribeId:2, code:"object.lWesterlandAF", xyz:[299,43,0]},
	{name:"Westerland (N)", id:133, tribeId:2, code:"object.lWesterlandN", xyz:[299,43,2]},
	{name:"Saint Malo AF", id:134, tribeId:2, code:"object.lSaintMaloAF", xyz:[131,97,0]},
	{name:"Saint Malo (N)", id:135, tribeId:2, code:"object.lSaintMaloN", xyz:[131,97,2]},
	{name:"Morlaix AF", id:136, tribeId:2, code:"object.lMorlaixAF", xyz:[97,93,0]},
	{name:"Morlaix (N)", id:137, tribeId:2, code:"object.lMorlaixN", xyz:[97,93,2]},
	{name:"Kings Cliffe AF", id:138, tribeId:1, code:"object.lKingsCliffeAF", xyz:[179,53,0]},
	{name:"Kings Cliff (N)", id:139, tribeId:1, code:"object.lKingsCliffN", xyz:[179,53,2]},
	{name:"Molesworth AF", id:140, tribeId:1, code:"object.lMolesworthAF", xyz:[175,55,0]},
	{name:"Molesworth (N)", id:141, tribeId:1, code:"object.lMolesworthN", xyz:[175,55,2]},
	{name:"Leeuwarden AF", id:142, tribeId:2, code:"object.lLeeuwardenAF", xyz:[253,61,0]},
	{name:"Leeuwarden (N)", id:143, tribeId:2, code:"object.lLeeuwardenN", xyz:[253,61,2]},
	{name:"Bretigny AF", id:144, tribeId:2, code:"object.lBretignyAF", xyz:[192,108,0]},
	{name:"Bretigny (N)", id:145, tribeId:2, code:"object.lBretignyN", xyz:[192,108,2]},
	{name:"Bron AF", id:146, tribeId:2, code:"object.lBronAF", xyz:[216,132,0]},
	{name:"Bron AF (N)", id:147, tribeId:2, code:"object.lBronAFN", xyz:[216,132,2]},
	{name:"St. Trond AF", id:148, tribeId:2, code:"object.lStTrondAF", xyz:[248,84,0]},
	{name:"St. Trond (N)", id:149, tribeId:2, code:"object.lStTrondN", xyz:[248,84,2]},
	{name:"Borkum AF", id:150, tribeId:2, code:"object.lBorkumAF", xyz:[259,55,0]},
	{name:"Borkum (N)", id:151, tribeId:2, code:"object.lBorkumN", xyz:[259,55,2]},
	{name:"Blankensee AF", id:152, tribeId:2, code:"object.lBlankenseeAF", xyz:[336,64,0]},
	{name:"Blankensee (N)", id:153, tribeId:2, code:"object.lBlankenseeN", xyz:[336,64,2]},
	{name:"Salzwedel AF", id:154, tribeId:2, code:"object.lSalzwedelAF", xyz:[333,83,0]},
	{name:"Salzwedel (N)", id:155, tribeId:2, code:"object.lSalzwedelN", xyz:[333,83,2]},
	{name:"Metz AF", id:156, tribeId:2, code:"object.lMetzAF", xyz:[263,99,0]},
	{name:"Metz (N)", id:157, tribeId:2, code:"object.lMetzN", xyz:[263,99,2]},
	{name:"Verdun", id:158, tribeId:2, code:"object.lVerdun", xyz:[247,109,0]},
]
// Flags
// (flags with the moduleName field specified won't appear here, but those don't work with
// canBuildSettings.lua anyway)
const flagsList = [
]
// Counter Keys
const countersList = [
]


const fullList = {}
const fullArray = [...unitList,...tribeList,...improvementList,...wonderList,...cityLocationList,...advancesList,...flagsList,...countersList]

fullArray.map( value => {
            fullList[value.code] = value;
    });


const testObject = false;

