--[[
OTR air combat roster — every combat airplane in object.lua
SAVE slots, flak, and bomb payloads omitted.
]]

local object = require("object")
local traits = require("traits")

local function registerCombatTraits()
    traits.allowedTraits(
        "dayFighter","nightFighter",
        "lowAltitude","highAltitude","allAltitude",
        "airSuperiority","bomberDestroyer","jabo",
        "lightBomber","mediumBomber","heavyBomber","wunderwaffe",
        "rocketArmed","fighter","bomber"
    )
end

local function A(unit, ...)
    if unit then traits.assign(unit, ...) end
end

local function assignTestSetTraits()
    A(object.uBf109G6, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uBf109G6R6, "fighter","dayFighter","allAltitude","bomberDestroyer","rocketArmed")
    A(object.uBf109G10, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uBf109G10R6, "fighter","dayFighter","allAltitude","bomberDestroyer","rocketArmed")
    A(object.uBf109G14, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uBf109G14R6, "fighter","dayFighter","allAltitude","bomberDestroyer","rocketArmed")
    A(object.uBf109K4, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uFw190A5, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uFw190A6, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uFw190A6R6, "fighter","dayFighter","lowAltitude","bomberDestroyer","rocketArmed")
    A(object.uFw190A8, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uFw190A8R6, "fighter","dayFighter","lowAltitude","bomberDestroyer","rocketArmed")
    A(object.uFw190D9, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uTa152, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uFw190F, "fighter","dayFighter","lowAltitude","jabo")
    A(object.uBf110G2, "fighter","dayFighter","lowAltitude","bomberDestroyer")
    A(object.uBf110G2R3, "fighter","dayFighter","lowAltitude","bomberDestroyer","rocketArmed")
    A(object.uBf110G4, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uMe210, "fighter","dayFighter","allAltitude","bomberDestroyer")
    A(object.uMe410B2, "fighter","dayFighter","allAltitude","bomberDestroyer")
    A(object.uMe410B2R3, "fighter","dayFighter","allAltitude","bomberDestroyer","rocketArmed")
    A(object.uHe219, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uDo217N2, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uJu88C6, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uJu88G, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uHe162A, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uMe163, "fighter","dayFighter","highAltitude","wunderwaffe","bomberDestroyer")
    A(object.uMe262, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uTa183, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uDo335, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uArado234, "bomber","mediumBomber","allAltitude","wunderwaffe")
    A(object.uGo229, "fighter","dayFighter","highAltitude","wunderwaffe")
    A(object.uHe177, "bomber","heavyBomber","highAltitude")
    A(object.uHe277, "bomber","heavyBomber","highAltitude")
    A(object.uJu188PR, "bomber","mediumBomber","allAltitude")
    A(object.uMS406, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uExperten, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uEgonMayer, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uHermannGraf, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uJosefPriller, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uAdolfGalland, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uGuntherRall, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uWalterNowotny, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uErichHartmann, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uHWSchnaufer, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uSpitfireMkV, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uSpitfireMkIXLF, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uSpitfireMkIX, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uSpitfireMkXIV, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uP47D6Thunderbolt, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uP47D15Thunderbolt, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uP47D20Thunderbolt, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uP47D25Thunderbolt, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uP47MThunderbolt, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uP38HLightning, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uP38JLightning, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uP38LLightning, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uP51BMustang, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uMustangIII, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uP51DMustang, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uMustangIV, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uWhirlwindIA, "fighter","dayFighter","lowAltitude","bomberDestroyer")
    A(object.uHurricaneIV, "fighter","dayFighter","lowAltitude","jabo")
    A(object.uMustangI, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uTyphoonIB, "fighter","dayFighter","lowAltitude","jabo")
    A(object.uTempestV, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uP80ShootingStar, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uMeteor, "fighter","dayFighter","allAltitude","airSuperiority","wunderwaffe")
    A(object.uBeaufighter, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uMosquitoNFII, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uMosquitoNFXIX, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uP61ABlackWidow, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uMedAirBeaufighter, "fighter","dayFighter","lowAltitude","bomberDestroyer")
    A(object.uP38JJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.uP38LJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.uP47D15Jabo, "fighter","dayFighter","highAltitude","jabo")
    A(object.uP47D20Jabo, "fighter","dayFighter","highAltitude","jabo")
    A(object.uP47D25Jabo, "fighter","dayFighter","highAltitude","jabo")
    A(object.uP51BJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.uMustangIIIJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.uP51DJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.uMustangIVJabo, "fighter","dayFighter","allAltitude","jabo")
    A(object.u332ndFighterGroup, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uFrancisGabreski, "fighter","dayFighter","highAltitude","airSuperiority")
    A(object.uGeorgePreddy, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uJohnBraham, "fighter","nightFighter","allAltitude","bomberDestroyer")
    A(object.uJohnnieJohnson, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uUSAce, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uUKAce, "fighter","dayFighter","allAltitude","airSuperiority")
    A(object.uBaltimoreV, "bomber","mediumBomber","lowAltitude")
    A(object.uBostonIII, "bomber","mediumBomber","lowAltitude")
    A(object.uWellington, "bomber","mediumBomber","lowAltitude")
    A(object.uStirling, "bomber","heavyBomber","lowAltitude")
    A(object.uHalifax, "bomber","heavyBomber","lowAltitude")
    A(object.uLancaster, "bomber","heavyBomber","lowAltitude")
    A(object.uLancasterPathfinder, "bomber","heavyBomber","lowAltitude")
    A(object.uMosquitoBIV, "bomber","lightBomber","allAltitude")
    A(object.uWellingtonRCM, "bomber","mediumBomber","lowAltitude")
    A(object.uA20GHavoc, "bomber","mediumBomber","lowAltitude")
    A(object.uA26BInvader, "bomber","mediumBomber","lowAltitude")
    A(object.uB25Mitchell, "bomber","mediumBomber","lowAltitude")
    A(object.uB26Marauder, "bomber","mediumBomber","lowAltitude")
    A(object.uB17FFortress, "bomber","heavyBomber","highAltitude")
    A(object.uB17FDamaged, "bomber","heavyBomber","highAltitude")
    A(object.uB17GFortress, "bomber","heavyBomber","highAltitude")
    A(object.uB17GDamaged, "bomber","heavyBomber","highAltitude")
    A(object.uB24Liberator, "bomber","heavyBomber","highAltitude")
    A(object.uB17Pathfinder, "bomber","heavyBomber","highAltitude")
    A(object.uB24Pathfinder, "bomber","heavyBomber","highAltitude")
    A(object.u15thAFB25, "bomber","mediumBomber","lowAltitude")
    A(object.u15thAFB24, "bomber","heavyBomber","highAltitude")
    A(object.uMedAirWellington, "bomber","mediumBomber","lowAltitude")
    A(object.uYak3, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uLa7, "fighter","dayFighter","lowAltitude","airSuperiority")
    A(object.uIl2, "fighter","dayFighter","lowAltitude","jabo")
    A(object.uMosquitoPR, "bomber","lightBomber","allAltitude")
end

local function fillTestParameters(combatParameters, makeCombatParameter)
    local function put(unit, row)
        if not unit then return end
        combatParameters[unit.id] = makeCombatParameter and makeCombatParameter(row) or row
    end
    local function AS(speed, crateA, crateD, pref, extra)
        extra = extra or {}
        extra.role = extra.role or "airSuperiority"
        extra.preferredMap = pref
        extra.pursuitSpeed = extra.pursuitSpeed or speed
        extra.escapeSpeed = extra.escapeSpeed or speed
        extra.luaAttack = crateA
        extra.luaDefense = crateD
        extra.luaFirepower = extra.luaFirepower or 2
        extra.gunFirepower = extra.gunFirepower or 2
        extra.interceptionRange = extra.interceptionRange or 2
        extra.attackMoveCost = extra.attackMoveCost or 10
        extra.attackModNight = extra.attackModNight or -2
        extra.defenseModNight = extra.defenseModNight or -2
        return extra
    end
    local function ace(unit, speed, crate, pref, role)
        put(unit, AS(speed, crate, crate-1, pref or "all", {role=role or "airSuperiority", interceptionRange=3, attackMoveCost=9}))
    end
    local function jabo(unit, speed, crateA, crateD, pref)
        put(unit, AS(speed-15, crateA, crateD, pref, {role="jabo"}))
    end
    local function hvy(unit, speed, defCrate, pref, guns)
        put(unit, {role="heavyBomber", preferredMap=pref or "high", pursuitSpeed=speed, escapeSpeed=speed+10, luaAttack=6, luaDefense=defCrate, luaFirepower=1, gunFirepower=guns or 2, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=255})
    end
    local function med(unit, speed, defCrate, pref)
        put(unit, {role="mediumBomber", preferredMap=pref or "low", pursuitSpeed=speed, escapeSpeed=speed+10, luaAttack=6, luaDefense=defCrate, luaFirepower=1, gunFirepower=2, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=255})
    end


    put(object.uBf109G6, AS(380, 10, 8, "all", {pursuitSpeedHigh=400, escapeSpeedHigh=400, attackModHigh=1, defenseModHigh=1}))
    put(object.uBf109G6R6, AS(355, 12, 7, "all", {role="bomberDestroyer", attackMoveCost=19}))
    put(object.uBf109G10, AS(400, 11, 8, "all", {pursuitSpeedHigh=420, escapeSpeedHigh=420, attackModHigh=1, defenseModHigh=1}))
    put(object.uBf109G10R6, AS(375, 13, 7, "all", {role="bomberDestroyer", attackMoveCost=20}))
    put(object.uBf109G14, AS(405, 11, 9, "all", {pursuitSpeedHigh=425, escapeSpeedHigh=425, attackModHigh=1, defenseModHigh=1}))
    put(object.uBf109G14R6, AS(380, 13, 7, "all", {role="bomberDestroyer", attackMoveCost=21}))
    put(object.uBf109K4, AS(445, 13, 9, "all", {pursuitSpeedHigh=470, escapeSpeedHigh=470, attackModHigh=2, defenseModHigh=2, attackMoveCost=12}))
    put(object.uFw190A5, AS(400, 11, 9, "low", {pursuitSpeedHigh=360, escapeSpeedHigh=360, attackModLow=1, defenseModLow=1, attackModHigh=-1, defenseModHigh=-1}))
    put(object.uFw190A6, AS(400, 11, 9, "low", {pursuitSpeedHigh=360, escapeSpeedHigh=360, attackModLow=1, defenseModLow=1, attackModHigh=-1, defenseModHigh=-1}))
    put(object.uFw190A6R6, AS(375, 13, 8, "low", {role="bomberDestroyer", attackMoveCost=29, pursuitSpeedHigh=350, escapeSpeedHigh=350, attackModLow=1, attackModHigh=-1}))
    put(object.uFw190A8, AS(405, 12, 10, "low", {pursuitSpeedHigh=380, escapeSpeedHigh=380, attackModLow=1, defenseModLow=1, attackModHigh=-1, defenseModHigh=-1, attackMoveCost=11}))
    put(object.uFw190A8R6, AS(380, 14, 8, "low", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=31, pursuitSpeedHigh=355, escapeSpeedHigh=355, attackModLow=1, attackModHigh=-1}))
    put(object.uFw190D9, AS(425, 13, 10, "all", {pursuitSpeedHigh=450, escapeSpeedHigh=450, attackModHigh=1, defenseModHigh=1, attackMoveCost=12}))
    put(object.uTa152, AS(470, 14, 10, "all", {pursuitSpeedHigh=495, escapeSpeedHigh=495, attackModHigh=2, defenseModHigh=2, interceptionRange=3, attackMoveCost=13}))
    put(object.uFw190F, AS(375, 11, 9, "low", {role="jabo", attackModLow=1, attackModHigh=-1}))
    put(object.uBf110G2, AS(340, 13, 8, "low", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=15, attackModLow=1, attackModHigh=-1}))
    put(object.uBf110G2R3, AS(320, 14, 7, "low", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=18, attackModHigh=-1}))
    put(object.uBf110G4, AS(320, 10, 8, "night", {role="bomberDestroyer", luaFirepower=3, pursuitSpeedNight=380, escapeSpeedNight=520, nightEscapeExtra=1.35, attackModNight=2, defenseModNight=2, attackModHigh=-2, attackModLow=-2, defenseModHigh=-2, defenseModLow=-2, attackMoveCost=12}))
    put(object.uMe210, AS(360, 12, 8, "all", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=16}))
    put(object.uMe410B2, AS(390, 13, 8, "all", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=17}))
    put(object.uMe410B2R3, AS(365, 14, 7, "all", {role="bomberDestroyer", luaFirepower=3, attackMoveCost=20}))
    put(object.uHe219, AS(420, 12, 9, "night", {role="bomberDestroyer", luaFirepower=3, pursuitSpeedNight=450, escapeSpeedNight=540, nightEscapeExtra=1.35, attackModNight=2, defenseModNight=2, attackModHigh=-2, attackModLow=-2, attackMoveCost=14}))
    put(object.uDo217N2, AS(320, 11, 8, "night", {role="bomberDestroyer", pursuitSpeedNight=340, escapeSpeedNight=480, nightEscapeExtra=1.25, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uJu88C6, AS(305, 11, 8, "night", {role="bomberDestroyer", pursuitSpeedNight=330, escapeSpeedNight=460, nightEscapeExtra=1.25, attackModNight=1, attackModHigh=-2, attackModLow=-2}))
    put(object.uJu88G, AS(345, 12, 8, "night", {role="bomberDestroyer", luaFirepower=3, pursuitSpeedNight=370, escapeSpeedNight=500, nightEscapeExtra=1.30, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uHe162A, AS(470, 13, 8, "all", {interceptionRange=3, attackMoveCost=5}))
    put(object.uMe163, AS(625, 15, 7, "high", {role="wunderwaffe", luaFirepower=3, interceptionRange=4, attackMoveCost=2, attackModHigh=2}))
    put(object.uMe262, AS(540, 15, 10, "all", {role="wunderwaffe", luaFirepower=3, interceptionRange=4, attackMoveCost=8, attackModHigh=1}))
    put(object.uTa183, AS(560, 15, 10, "all", {role="wunderwaffe", interceptionRange=4, attackMoveCost=8}))
    put(object.uDo335, AS(475, 13, 10, "all", {attackMoveCost=13}))
    put(object.uGo229, AS(620, 14, 9, "high", {role="wunderwaffe", interceptionRange=4}))
    put(object.uMS406, AS(300, 7, 7, "low", {attackModHigh=-2}))
    put(object.uHe177, {role="heavyBomber", preferredMap="high", pursuitSpeed=270, escapeSpeed=280, luaAttack=6, luaDefense=11, luaFirepower=1, gunFirepower=2, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=22})
    put(object.uHe277, {role="heavyBomber", preferredMap="high", pursuitSpeed=285, escapeSpeed=295, luaAttack=6, luaDefense=12, luaFirepower=1, gunFirepower=2, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=23})
    put(object.uArado234, {role="mediumBomber", preferredMap="all", pursuitSpeed=460, escapeSpeed=460, luaAttack=7, luaDefense=9, luaFirepower=1, gunFirepower=1, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=10})
    put(object.uJu188PR, {role="mediumBomber", preferredMap="all", pursuitSpeed=325, escapeSpeed=325, luaAttack=5, luaDefense=8, gunFirepower=1, interceptionRange=0, attackMoveCost=60})
    ace(object.uExperten, 475, 14)
    ace(object.uEgonMayer, 500, 15)
    ace(object.uHermannGraf, 500, 15)
    ace(object.uJosefPriller, 500, 15)
    ace(object.uAdolfGalland, 600, 16)
    ace(object.uGuntherRall, 500, 15)
    ace(object.uWalterNowotny, 600, 16)
    ace(object.uErichHartmann, 500, 16)
    put(object.uHWSchnaufer, AS(500, 14, 10, "night", {role="bomberDestroyer", pursuitSpeedNight=520, escapeSpeedNight=560, nightEscapeExtra=1.40, attackModNight=2, defenseModNight=2, interceptionRange=3}))
    put(object.uSpitfireMkV, AS(360, 9, 8, "all", {attackModLow=1}))
    put(object.uSpitfireMkIXLF, AS(390, 11, 9, "low", {attackModLow=1, defenseModLow=1, attackModHigh=-1}))
    put(object.uSpitfireMkIX, AS(400, 11, 9, "all", {pursuitSpeedHigh=410, escapeSpeedHigh=420, attackModHigh=1, attackModLow=1, defenseModHigh=1, defenseModLow=1}))
    put(object.uSpitfireMkXIV, AS(445, 13, 10, "all", {pursuitSpeedHigh=460, escapeSpeedHigh=460, attackModHigh=1, attackMoveCost=12}))
    put(object.uP47D6Thunderbolt, AS(370, 11, 10, "high", {pursuitSpeedHigh=420, escapeSpeedHigh=430, pursuitSpeedLow=340, escapeSpeedLow=350, attackModHigh=2, defenseModHigh=2, attackModLow=-2, defenseModLow=-2, defenseModDive=3}))
    put(object.uP47D15Thunderbolt, AS(380, 12, 11, "high", {pursuitSpeedHigh=430, escapeSpeedHigh=440, pursuitSpeedLow=350, escapeSpeedLow=360, attackModHigh=2, defenseModHigh=2, attackModLow=-2, defenseModLow=-2, defenseModDive=3}))
    put(object.uP47D20Thunderbolt, AS(390, 12, 11, "high", {pursuitSpeedHigh=440, escapeSpeedHigh=450, pursuitSpeedLow=355, escapeSpeedLow=365, attackModHigh=2, defenseModHigh=2, attackModLow=-2, defenseModLow=-2, defenseModDive=3}))
    put(object.uP47D25Thunderbolt, AS(400, 13, 12, "high", {pursuitSpeedHigh=450, escapeSpeedHigh=460, pursuitSpeedLow=360, escapeSpeedLow=370, attackModHigh=2, defenseModHigh=2, attackModLow=-2, defenseModLow=-2, defenseModDive=3}))
    put(object.uP47MThunderbolt, AS(450, 14, 12, "high", {pursuitSpeedHigh=480, escapeSpeedHigh=490, attackModHigh=2, defenseModHigh=2, attackModLow=-1, defenseModLow=-2, defenseModDive=3, interceptionRange=3}))
    put(object.uP38HLightning, AS(390, 11, 9, "all"))
    put(object.uP38JLightning, AS(410, 12, 10, "all"))
    put(object.uP38LLightning, AS(420, 12, 10, "all"))
    put(object.uP51BMustang, AS(430, 13, 10, "all", {pursuitSpeedHigh=450, escapeSpeedHigh=455, interceptionRange=3, attackMoveCost=11}))
    put(object.uMustangIII, AS(430, 13, 10, "all", {pursuitSpeedHigh=450, escapeSpeedHigh=455, interceptionRange=3, attackMoveCost=11}))
    put(object.uP51DMustang, AS(440, 14, 10, "all", {pursuitSpeedHigh=460, escapeSpeedHigh=465, interceptionRange=3, attackMoveCost=12}))
    put(object.uMustangIV, AS(440, 14, 10, "all", {pursuitSpeedHigh=460, escapeSpeedHigh=465, interceptionRange=3, attackMoveCost=12}))
    put(object.uWhirlwindIA, AS(360, 11, 8, "low", {role="bomberDestroyer"}))
    put(object.uHurricaneIV, AS(330, 10, 8, "low", {role="jabo", attackModLow=1}))
    put(object.uMustangI, AS(380, 10, 8, "low", {attackModLow=1}))
    put(object.uTyphoonIB, AS(400, 12, 9, "low", {role="jabo", attackModLow=1, attackModHigh=-1}))
    put(object.uTempestV, AS(430, 13, 10, "low", {attackModLow=1, interceptionRange=3}))
    put(object.uP80ShootingStar, AS(530, 15, 10, "all", {role="wunderwaffe", interceptionRange=4, attackMoveCost=8}))
    put(object.uMeteor, AS(500, 14, 10, "all", {role="wunderwaffe", interceptionRange=4, attackMoveCost=8}))
    put(object.uBeaufighter, AS(320, 11, 8, "night", {role="bomberDestroyer", pursuitSpeedNight=360, escapeSpeedNight=480, nightEscapeExtra=1.25, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uMosquitoNFII, AS(360, 12, 9, "night", {role="bomberDestroyer", pursuitSpeedNight=400, escapeSpeedNight=520, nightEscapeExtra=1.30, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uMosquitoNFXIX, AS(380, 13, 9, "night", {role="bomberDestroyer", pursuitSpeedNight=420, escapeSpeedNight=540, nightEscapeExtra=1.35, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uP61ABlackWidow, AS(350, 13, 10, "night", {role="bomberDestroyer", luaFirepower=3, pursuitSpeedNight=390, escapeSpeedNight=500, nightEscapeExtra=1.30, attackModNight=2, attackModHigh=-2, attackModLow=-2}))
    put(object.uMedAirBeaufighter, AS(320, 11, 8, "low", {role="bomberDestroyer"}))
    jabo(object.uP38JJabo, 410, 12, 10, "all")
    jabo(object.uP38LJabo, 420, 12, 10, "all")
    jabo(object.uP47D15Jabo, 380, 12, 11, "high")
    jabo(object.uP47D20Jabo, 390, 12, 11, "high")
    jabo(object.uP47D25Jabo, 400, 13, 12, "high")
    jabo(object.uP51BJabo, 430, 13, 10, "all")
    jabo(object.uMustangIIIJabo, 430, 13, 10, "all")
    jabo(object.uP51DJabo, 440, 14, 10, "all")
    jabo(object.uMustangIVJabo, 440, 14, 10, "all")
    ace(object.u332ndFighterGroup, 440, 14)
    ace(object.uFrancisGabreski, 450, 15, "high")
    ace(object.uGeorgePreddy, 460, 15)
    ace(object.uJohnnieJohnson, 450, 15)
    ace(object.uUSAce, 450, 14)
    ace(object.uUKAce, 450, 14)
    put(object.uJohnBraham, AS(400, 14, 10, "night", {role="bomberDestroyer", pursuitSpeedNight=440, escapeSpeedNight=540, nightEscapeExtra=1.35, attackModNight=2, interceptionRange=3}))
    hvy(object.uB17FFortress, 250, 12, "high", 2)
    hvy(object.uB17GFortress, 250, 13, "high", 2)
    hvy(object.uB17FDamaged, 230, 9, "high", 1)
    hvy(object.uB17GDamaged, 230, 10, "high", 1)
    hvy(object.uB24Liberator, 260, 12, "high", 2)
    hvy(object.uB17Pathfinder, 250, 12, "high", 2)
    hvy(object.uB24Pathfinder, 260, 12, "high", 2)
    hvy(object.u15thAFB24, 260, 12, "high", 2)
    hvy(object.uStirling, 240, 11, "low", 2)
    hvy(object.uHalifax, 250, 12, "low", 2)
    hvy(object.uLancaster, 250, 11, "low", 2)
    hvy(object.uLancasterPathfinder, 250, 11, "low", 2)
    med(object.uBaltimoreV, 280, 9, "low")
    med(object.uBostonIII, 300, 9, "low")
    med(object.uWellington, 235, 10, "low")
    med(object.uWellingtonRCM, 235, 10, "low")
    med(object.uMedAirWellington, 235, 10, "low")
    med(object.uA20GHavoc, 310, 9, "low")
    med(object.uA26BInvader, 330, 10, "low")
    med(object.uB25Mitchell, 275, 10, "low")
    med(object.uB26Marauder, 280, 10, "low")
    med(object.u15thAFB25, 275, 10, "low")
    put(object.uMosquitoBIV, {role="lightBomber", preferredMap="all", pursuitSpeed=360, escapeSpeed=380, luaAttack=6, luaDefense=8, gunFirepower=1, alwaysReturnFire=true, interceptionRange=0, attackMoveCost=12})
    put(object.uMosquitoPR, {role="lightBomber", preferredMap="all", pursuitSpeed=370, escapeSpeed=390, luaAttack=4, luaDefense=7, gunFirepower=1, interceptionRange=0, attackMoveCost=60})
    put(object.uYak3, AS(400, 12, 9, "low", {attackModLow=1, attackModHigh=-1}))
    put(object.uLa7, AS(410, 12, 9, "low", {attackModLow=1, attackModHigh=-1}))
    put(object.uIl2, AS(250, 10, 10, "low", {role="jabo", attackModLow=1, attackModHigh=-2}))
end

return {
    registerCombatTraits = registerCombatTraits,
    assignTestSetTraits = assignTestSetTraits,
    fillTestParameters = fillTestParameters,
}
